server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/jim_where
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
  
  sql:
    init:
      mode: always
      encoding: UTF-8

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 900000      # 15?
  refresh-expiration: 3600000    # 1??

auth:
  code:
    expiration-millis: 300000

data:
  go:
    kr:
      service-key: ${BUSINESS_KEY}


coolsms:
  api-key: ${COOLSMS_API_KEY}
  api-secret: ${COOLSMS_API_SECRET}
  from-number: ${COOLSMS_FROM_NUMBER}

toss:
  payments:
    secret-key: ${TOSS_SECRET_KEY}
    base-url: ${TOSS_BASE_URL}
    client-key: ${TOSS_CLIENT_KEY}
    success-url: ${TOSS_SUCCESS_URL}
    fail-url: ${TOSS_FAIL_URL}